### ISSUE TITLE
Having "KeyError: 'LOG_PATH'" While Docker Running

### ISSUE THREAD

**Issue by a79687417** [ailabstw/FLaVor#5]
In my model training code, I didn't use the key of 'LOG_PATH', and in flavor manual it says 'LOG_PATH' is optional, so I didn't expect this to happen.
My whole error message:
```
Traceback (most recent call last):
  File "/opt/conda/bin/flavor-fl", line 31, in <module>
    main()
  File "/opt/conda/bin/flavor-fl", line 23, in main
    from flavor.cook.servicer import EdgeAppServicer, serve
  File "/opt/conda/lib/python3.7/site-packages/flavor/cook/servicer.py", line 43, in <module>
    logger_path = os.path.join(os.environ["LOG_PATH"], "appService.log")
  File "/opt/conda/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOG_PATH'
```

**Comment by a79687417** [comment]
Apparently I didn't read the manual carefully and use the correct command to run the docker. Though it's nearly impossible for other users to have this issue, just a reminder, use the following command given in manual instead of simply "docker run foo:v0": 
`
docker run -id --rm --gpus all --runtime=nvidia --shm-size=64g -v ./CoPI/dataset:/data -v ./weights/:/weights -w /app --name foo_test foo:v0 sleep inf &
`
